- pipeline.id: service_stamped_nginx
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "/usr/share/logstash/config/pipelines/service_stamped_nginx_fb.conf"

# - pipeline.id: service_stamped_redis
#   pipeline.workers: 1
#   pipeline.batch.size: 1
#   path.config: "/usr/share/logstash/config/pipelines/service_stamped_redis.conf.conf"
